"use strict";

module.exports = {
  up: async (queryInterface, Sequelize) => {
    console.log("Seeding packages");
    await queryInterface.bulkInsert("Networks", [{ name: "ABC", createdAt: new Date(), updatedAt: new Date() },
    { name: "BET", createdAt: new Date(), updatedAt: new Date() },
    { name: "Bravo", createdAt: new Date(), updatedAt: new Date() },
    { name: "CBS", createdAt: new Date(), updatedAt: new Date() },
    { name: "CW", createdAt: new Date(), updatedAt: new Date() },
    { name: "Freeform", createdAt: new Date(), updatedAt: new Date() },
    { name: "HBO", createdAt: new Date(), updatedAt: new Date() },
    { name: "NBC", createdAt: new Date(), updatedAt: new Date() },
    { name: "Nickelodeon", createdAt: new Date(), updatedAt: new Date() },
    { name: "Showtime", createdAt: new Date(), updatedAt: new Date() },
    { name: "STARZ", createdAt: new Date(), updatedAt: new Date() },
    ]);
    await queryInterface.bulkInsert("Shows", [{
      title: "A Little Late With Lilly Singh",
      network: "NBC",
      imdbRating: 1.5,
      network_id: 8,
      package_id: "1,2,3,4",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: "American Gods",
      network: "STARZ",
      imdbRating: 7.7,
      network_id: 11,
      package_id: "2",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: "American Idol",
      network: "ABC",
      imdbRating: 4.1,
      network_id: 1,
      package_id: "1,2,3,4",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: "Below Deck",
      network: "Bravo",
      imdbRating: 7.3,
      network_id: 3,
      package_id: "2,3,4",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: "Big Little Lies",
      network: "HBO",
      imdbRating: 8.5,
      network_id: 7,
      package_id: "2,4",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: "black-ish",
      network: "ABC",
      imdbRating: 7.1,
      network_id: 1,
      package_id: "1,2,3,4",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: "Bunheads",
      network: "Freeform",
      imdbRating: 7.6,
      network_id: 6,
      package_id: "2,3,4",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: "Dexter",
      network: "Showtime",
      imdbRating: 8.6,
      network_id: 10,
      package_id: "2,4",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: "Everything's Gonna Be Okay",
      network: "Freeform",
      imdbRating: 7.3,
      network_id: 6,
      package_id: "2,3,4",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: "Mom",
      network: "CBS",
      imdbRating: 7.2,
      network_id: 4,
      package_id: "1,2,3,4",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: "Outlander",
      network: "STARZ",
      imdbRating: 8.4,
      network_id: 11,
      package_id: "2",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: "Rebel",
      network: "BET",
      imdbRating: 5.4,
      network_id: 2,
      package_id: "1,2,3,4",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: "Riverdale",
      network: "CW",
      imdbRating: 6.8,
      network_id: 5,
      package_id: "1,2,3,4",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: "Silicon Valley",
      network: "HBO",
      imdbRating: 8.5,
      network_id: 7,
      package_id: "2,4",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: "Southern Charm",
      network: "Bravo",
      imdbRating: 6.2,
      network_id: 3,
      package_id: "2,3,4",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: "SpongeBob SquarePants",
      network: "Nickelodeon",
      imdbRating: 8.2,
      network_id: 9,
      package_id: "2,3,4",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: "Rocket Power",
      network: "Nickelodeon",
      imdbRating: 6.2,
      network_id: 9,
      package_id: "2,3,4",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: "The Amazing Race",
      network: "CBS",
      imdbRating: 7.6,
      network_id: 4,
      package_id: "1,2,3,4",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: "The Fosters",
      network: "Freeform",
      imdbRating: 7.9,
      network_id: 6,
      package_id: "2,3,4",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: "Top Chef",
      network: "Bravo",
      imdbRating: 7.6,
      network_id: 3,
      package_id: "2,3,4",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: "Tyler Perry's The Oval",
      network: "BET",
      imdbRating: 4,
      network_id: 2,
      package_id: "1,2,3,4",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: "Zoey's Extraordinary Playlist",
      network: "NBC",
      imdbRating: 8.1,
      network_id: 8,
      package_id: "1,2,3,4",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    ]);
    await queryInterface.bulkInsert("Packages", [
      { name: "Basic", networks: 'CBS, CW, ABC, NBC', price: 9.9, createdAt: new Date(), updatedAt: new Date() },
      {
        name: "Gold",
        networks: 'CBS, CW, ABC, NBC, BET, Freeform, Nickelodeon, Bravo, HBO, Showtime, STARZ',
        price: 37.9,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Select",
        networks: 'CBS, CW, ABC, NBC, BET, Freeform, Nickelodeon, Bravo',
        price: 17.9,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Silver",
        networks: 'CBS, CW, ABC, NBC, BET, Freeform, Nickelodeon, Bravo, HBO, Showtime',
        price: 27.9,
        createdAt: new Date(),
        updatedAt: new Date()
      },
    ]);
  },

  down: async (queryInterface, Sequelize) => {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
    await queryInterface.bulkDelete("Packages", null, {});
    await queryInterface.bulkDelete("Shows", null, {});
    await queryInterface.bulkDelete("Networks", null, {});
  },
};
